### ISSUE TITLE
npm run build:prepare don't work on Windows Command prompt

### ISSUE THREAD

**Issue by jeansamist** [rasengan-dev/rasenganjs#12]
When a user runs the build prepare command on the Windows command prompt, he has an error because rasengan uses some commands not on the Windows system32.
![image](https://github.com/user-attachments/assets/7ad8cd6d-d623-48ab-b4bb-250c852ca3ae)

**Comment by dilane3** [comment]
Thanks @jeansamist for your contribution.

The issue is about the system environment on which the project is working. On windows there is no command called **cp** that exists, the equivalent one is **copy**.

We have to check the system type first during the execution of the build:prepare command.

So this issue will be resolved in the next release.

**Comment by dilane3** [comment]
Solved in #13
